# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

BOX_IMAGE =  "boxcutter/ubuntu1604-desktop"
BOX_VERSION = "17.0907.1"
VBVM_MEMORY = 1024
LAB = "packet"
VBVM_NAME01 = LAB+"vm1"
VBVM_NAME02 = LAB+"vm2"
VBVM_NAME03 = LAB+"vm3"
VBVM_NAME04 = LAB+"vm4"
VBVM_NAME05 = LAB+"vm5"
VBVM_NAME06 = LAB+"vm6"
VM_HOSTNAME01 = "vm1"
VM_HOSTNAME02 = "vm2"
VM_HOSTNAME03 = "vm3"
VM_HOSTNAME04 = "vm4"
VM_HOSTNAME05 = "vm5"
VM_HOSTNAME06 = "vm6"
IPIF1_HOST1 = "192.168.10.1"
IPIF1_HOST2 = "192.168.10.2"
IPIF2_HOST2 = "192.168.20.1"
IPIF1_HOST3 = "192.168.20.2"
IPIF_DEFAULT_GW = "10.0.2.2"
XARXA1 = "lan1"
XARXA2 = "lan2"

Vagrant.configure("2") do |config|
## fem que no s'engege fins que preparem el servidor (vm2)
  config.ssh.forward_x11 = true
  config.vm.define VM_HOSTNAME01, autostart: true  do |subconfig|
    subconfig.vm.provider "virtualbox" do |vb|
## tractar d'evitar IOERROR
## ??       vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]

       vb.name = VBVM_NAME01 
       vb.memory = VBVM_MEMORY
       vb.linked_clone = true
       vb.gui = true
    end

    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.box_version = BOX_VERSION
    subconfig.vm.hostname = VM_HOSTNAME01 
    subconfig.vm.network :private_network, ip: IPIF1_HOST1, virtualbox__intnet: XARXA1, auto_config: true
    subconfig.vm.provision :shell, path: "bootstrap-vm1.sh"
    
#  accions a realitzar sobre la màquina vm1 
##  -- no per lab13
##    subconfig.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
##    subconfig.vm.provision "shell", inline: <<-SHELL
##     sudo route add -net 192.168.20.0/24 enp0s8
##    SHELL

  end
  end
